#!/usr/bin/env python3
"""Generate docs/reference/metrics.md by scanning every Rust crate for
`metrics::counter!`, `metrics::gauge!`, `metrics::histogram!` invocations.

The source of truth is the call sites themselves. We extract:
  - The metric name (first string literal)
  - The label keys (each `"key" =>` arm)
  - The metric kind (counter / gauge / histogram)
  - The file:line where it lives (for grep-back)

A small `METRIC_META` table provides unit + description for each metric
(maintained by hand here — Prometheus / OpenMetrics doesn't allow embedding
descriptions in the call macro, so this is the trade-off).
"""
from __future__ import annotations

import re
import sys
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
OUTPUT = REPO / "docs/reference/metrics.md"

CALL_RX = re.compile(
    # metrics::counter!(\n      "name",\n      "label" => expr,\n      ...\n  )
    # or single-line
    r"metrics::(?P<kind>counter|gauge|histogram)!\s*\(\s*"
    r'"(?P<name>[a-z_][a-z0-9_]*)"\s*(?P<labels>(?:,\s*"[^"]+"\s*=>\s*[^,)]+)*)\s*\)',
    re.MULTILINE,
)

LABEL_RX = re.compile(r'"(?P<key>[a-z_][a-z0-9_]*)"\s*=>')


METRIC_META: dict[str, dict[str, str]] = {
    "http_requests_total": {
        "unit": "requests",
        "desc": "Count of HTTP requests handled by the backend, labelled by HTTP method and response status code. Use this to compute request rate and the error ratio (rate by status=~\"5..\").",
    },
    "http_request_duration_seconds": {
        "unit": "seconds",
        "desc": "Histogram of HTTP request latency. Use the standard `_bucket` series for P50/P95/P99 quantiles; `_sum / _count` gives the mean.",
    },
    "ws_connections_active": {
        "unit": "connections",
        "desc": "Open WebSocket connections to the backend hub at sampling time (frontend + gateways). Sampled every 5 seconds by a background task.",
    },
    "agents_connected": {
        "unit": "agents",
        "desc": "Number of unique agents currently routed through the WebSocket hub. Diverges from the total agent count when an agent is registered in the DB but disconnected.",
    },
    "db_pool_connections": {
        "unit": "connections",
        "desc": "Postgres / SQLite connection-pool occupancy. Label `state` is one of `idle`, `active`, `total` — alert on `total ≥ DB_POOL_SIZE` for sustained periods.",
    },
    "db_type_info": {
        "unit": "info",
        "desc": "Constant gauge (`= 1`) labelled with `type=postgres` or `type=sqlite`, exposing the compile-time database backend.",
    },
    "commands_executed_total": {
        "unit": "commands",
        "desc": "Count of custom commands dispatched to agents via `POST /components/:id/command/:cmd`. Labelled by command name.",
    },
    "state_transitions_total": {
        "unit": "transitions",
        "desc": "Count of FSM transitions persisted to `state_transitions`. Labelled with `from` and `to` (uppercase state names). Heartbeat-timeout transitions show `to=\"UNREACHABLE\"`.",
    },
    "agent_message_latency_ms": {
        "unit": "milliseconds",
        "desc": "End-to-end latency between an agent emitting a message and the backend processing it (the message's `at` timestamp minus server-side receive time). Labelled by `message_type`.",
    },
}


def scan() -> list[dict]:
    rows = []
    for path in sorted(REPO.glob("crates/**/src/**/*.rs")):
        if "/tests/" in str(path):
            continue
        text = path.read_text()
        for m in CALL_RX.finditer(text):
            labels = [lm.group("key") for lm in LABEL_RX.finditer(m.group("labels"))]
            # Compute line number for grep-back.
            line = text.count("\n", 0, m.start()) + 1
            rows.append({
                "name": m.group("name"),
                "kind": m.group("kind"),
                "labels": labels,
                "where": f"{path.relative_to(REPO)}:{line}",
            })
    return rows


def merge(rows: list[dict]) -> dict[str, dict]:
    """Collapse multiple call sites for the same metric into a single entry,
    union-ing the label sets and collecting source locations."""
    merged: dict[str, dict] = {}
    for r in rows:
        slot = merged.setdefault(r["name"], {
            "name": r["name"],
            "kind": r["kind"],
            "labels": set(),
            "where": set(),
        })
        slot["labels"].update(r["labels"])
        slot["where"].add(r["where"])
        # If kinds disagree across call sites, that's a bug — flag it visibly.
        if slot["kind"] != r["kind"]:
            slot["kind"] = f"{slot['kind']}/{r['kind']}!CONFLICT"
    return merged


def render(merged: dict[str, dict]) -> str:
    out = []
    out.append("# Metrics reference")
    out.append("")
    out.append("> Auto-generated by scanning `crates/**/src/**/*.rs` for `metrics::{counter,gauge,histogram}!` invocations. Run `scripts/docs/regen.py` to refresh.")
    out.append("")
    out.append("The backend exposes Prometheus metrics at `GET /metrics`. The endpoint requires no authentication by default; restrict it at the load-balancer or reverse-proxy layer if you do not want it scraped from the public network.")
    out.append("")
    out.append("```bash")
    out.append("# Local check")
    out.append("curl -s http://localhost:3000/metrics | head -40")
    out.append("")
    out.append("# Prometheus scrape config snippet")
    out.append("# (see monitoring/prometheus/prometheus.yml for the full file)")
    out.append("scrape_configs:")
    out.append("  - job_name: appcontrol-backend")
    out.append("    metrics_path: /metrics")
    out.append("    static_configs:")
    out.append("      - targets: ['backend:3000']")
    out.append("```")
    out.append("")
    out.append("## Exposed metrics")
    out.append("")
    out.append("| Name | Kind | Unit | Labels | Description |")
    out.append("|---|---|---|---|---|")
    for name in sorted(merged):
        m = merged[name]
        meta = METRIC_META.get(name, {})
        labels = ", ".join(f"`{l}`" for l in sorted(m["labels"])) or "_(none)_"
        out.append(
            f"| `{name}` | {m['kind']} | {meta.get('unit', '_?_')} | {labels} | {meta.get('desc', '_(undocumented)_')} |"
        )
    out.append("")
    out.append("## Call sites")
    out.append("")
    out.append("If you need to trace a metric back to the code that emits it:")
    out.append("")
    out.append("| Metric | Source |")
    out.append("|---|---|")
    for name in sorted(merged):
        wheres = sorted(merged[name]["where"])
        out.append(f"| `{name}` | {', '.join(f'`{w}`' for w in wheres)} |")
    out.append("")
    out.append("## Recommended alerts")
    out.append("")
    out.append("Three baseline alerts cover most real outages:")
    out.append("")
    out.append("```yaml")
    out.append("groups:")
    out.append("  - name: appcontrol")
    out.append("    rules:")
    out.append("      - alert: BackendErrorRateHigh")
    out.append("        expr: |")
    out.append("          sum(rate(http_requests_total{status=~\"5..\"}[5m]))")
    out.append("            / sum(rate(http_requests_total[5m])) > 0.02")
    out.append("        for: 10m")
    out.append("        annotations:")
    out.append("          summary: \">2% 5xx on the backend for 10 minutes\"")
    out.append("")
    out.append("      - alert: DbPoolSaturated")
    out.append("        expr: db_pool_connections{state=\"total\"} >= 18")
    out.append("        for: 5m")
    out.append("        annotations:")
    out.append("          summary: \"DB pool ≥90% of DB_POOL_SIZE for 5 minutes — increase pool or investigate slow queries\"")
    out.append("")
    out.append("      - alert: AgentMessageLatencyHigh")
    out.append("        expr: histogram_quantile(0.95, rate(agent_message_latency_ms_bucket[5m])) > 5000")
    out.append("        for: 10m")
    out.append("        annotations:")
    out.append("          summary: \"P95 agent → backend latency above 5s — check gateway, network, or backend CPU\"")
    out.append("```")
    out.append("")
    out.append("## See also")
    out.append("")
    out.append("- [Check command metrics](../METRICS.md) — the *application*-level metrics extracted from your `check_cmd` stdout (queue depth, replication lag, etc.). These are stored in `check_events.metrics` JSON and surfaced in the UI, separately from the Prometheus metrics documented on this page.")
    out.append("- [Capacity planning](../CAPACITY_PLANNING.md) — sizing the backend based on metric load.")
    out.append("")
    return "\n".join(out)


def main() -> int:
    rows = scan()
    merged = merge(rows)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render(merged))
    print(f"metrics: {len(merged)} metrics from {len(rows)} call sites → {OUTPUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
