#!/usr/bin/env python3
"""Generate docs/reference/mcp.md by reading the MCP tool dispatcher in
`crates/mcp/src/tools.rs`.

The tool list is the `match name { ... }` block in `McpClient::call_tool`.
We pair each tool name with the arguments it extracts and the REST endpoint
it calls, plus a short description editable in `TOOL_DESC` below.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SOURCE = REPO / "crates/mcp/src/tools.rs"
OUTPUT = REPO / "docs/reference/mcp.md"


TOOL_DESC = {
    "list_apps": ("List every application the API key can see.", []),
    "get_app_status": ("Return current overall status, per-component states, and the FSM transition history for an application.", ["app_name"]),
    "start_app": ("Start an application in DAG order. Pass `dry_run=true` to validate the plan without dispatching.", ["app_name", "dry_run"]),
    "stop_app": ("Stop an application in reverse-DAG order.", ["app_name"]),
    "diagnose_app": ("Run the 3-level diagnostic (Health / Integrity / Infrastructure) and return the recommendation matrix.", ["app_name"]),
    "get_incidents": ("Return incidents (FSM transitions to FAILED) over the last `days` days. Default: 7 days.", ["app_name", "days"]),
    "get_topology": ("Return the DAG: nodes, edges (strong/weak), groups, and per-component metadata.", ["app_name"]),
    "estimate_time": ("Estimate how long `operation` (`start` or `stop`) will take based on historical execution times for this application.", ["app_name", "operation"]),
    "get_activity": ("Return the most recent rows from `action_log` for this application, capped by `limit` (default 20).", ["app_name", "limit"]),
    "list_agents": ("List enrolled agents with hostname, last heartbeat, and version.", []),
    "list_log_sources": ("List the log streams an agent exposes for a given component (declared in `log_sources` on the component).", ["app_name", "component_name"]),
    "get_component_logs": ("Tail the last N lines from a component log stream. Useful for `claude code`-driven incident analysis.", ["app_name", "component_name", "source", "lines"]),
}


def parse_tools() -> list[str]:
    text = SOURCE.read_text()
    # Find every `"name" => self.something(...)` in the dispatcher.
    rx = re.compile(r'"([a-z_][a-z0-9_]*)"\s*=>')
    names = []
    seen = set()
    for m in rx.finditer(text):
        name = m.group(1)
        if name in seen:
            continue
        seen.add(name)
        names.append(name)
    return names


def render(names: list[str]) -> str:
    out = []
    out.append("# MCP tool reference")
    out.append("")
    out.append("> Auto-generated by scanning `crates/mcp/src/tools.rs`. Run `scripts/docs/regen.py` to refresh.")
    out.append("")
    out.append("AppControl ships an MCP (Model Context Protocol) server that exposes the production stack to any MCP-compatible client: Claude Desktop, Claude Code, Cursor, ChatGPT (via bridge), and others. The MCP server is a thin shim — every tool call resolves to one REST API call, with the same auth and audit semantics as a CLI or UI call. Every MCP-triggered action lands in `action_log` with `actor_type='mcp'`.")
    out.append("")
    out.append("## Setup")
    out.append("")
    out.append("```jsonc")
    out.append("// ~/.config/claude-desktop/claude_desktop_config.json")
    out.append("{")
    out.append('  "mcpServers": {')
    out.append('    "appcontrol": {')
    out.append('      "command": "appcontrol-mcp",')
    out.append('      "args": ["--url", "https://appcontrol.example.com"],')
    out.append('      "env": {')
    out.append('        "APPCONTROL_API_KEY": "ac_xxxxxxxxxxxx"')
    out.append("      }")
    out.append("    }")
    out.append("  }")
    out.append("}")
    out.append("```")
    out.append("")
    out.append("The MCP binary is shipped alongside the backend; run `appcontrol-mcp --help` for the version-specific flags.")
    out.append("")
    out.append("## Tools")
    out.append("")
    out.append(f"**{len(names)}** tools exposed.")
    out.append("")
    out.append("| Tool | Required args | Description |")
    out.append("|---|---|---|")
    for n in names:
        desc, args = TOOL_DESC.get(n, ("_(undocumented — add to `scripts/docs/gen_mcp.py::TOOL_DESC`)_", []))
        args_md = ", ".join(f"`{a}`" for a in args) if args else "_(none)_"
        out.append(f"| `{n}` | {args_md} | {desc} |")
    out.append("")
    out.append("## Permissions and audit")
    out.append("")
    out.append("MCP requests authenticate with the same API keys as the CLI and REST API:")
    out.append("")
    out.append("- The key carries the user's effective permission. `start_app` on an application where the key has only `View` returns the same `forbidden` error as the REST endpoint would.")
    out.append("- Every tool call is recorded in `action_log` with `actor_type='mcp'` and the tool name in `action_log.action`. Audit reports surface MCP-triggered actions identically to UI-triggered ones.")
    out.append("- Read-only tools (`list_apps`, `get_app_status`, …) still appear in the audit trail — DORA Article 16 requires every access to be loggable, not just mutations.")
    out.append("")
    out.append("## Example session (Claude Desktop)")
    out.append("")
    out.append("```")
    out.append("User:  Which components of core-banking failed in the last 24h?")
    out.append("Claude: [calls get_incidents(app_name='core-banking', days=1)]")
    out.append("       Two components transitioned to FAILED in the last 24h:")
    out.append("       — batch-eod (07:14 UTC, exit_code=2)")
    out.append("       — settlement-queue (11:02 UTC, exit_code=1, recovered at 11:08)")
    out.append("")
    out.append("User:  Show me the last 40 lines of batch-eod's stderr.")
    out.append("Claude: [calls get_component_logs(app_name='core-banking', component_name='batch-eod', source='stderr', lines=40)]")
    out.append("```")
    out.append("")
    return "\n".join(out)


def main() -> int:
    names = parse_tools()
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render(names))
    print(f"mcp: {len(names)} tools → {OUTPUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
