//! Agent enrollment: obtain mTLS certificates from the backend via a one-time token.
//!
//! Usage: `appcontrol-agent --enroll <gateway-url> --token <enrollment-token>`
//!
//! Flow:
//! 1. POST to gateway /enroll with token + hostname
//! 2. Gateway proxies to backend /api/v1/enroll
//! 3. Backend validates token, generates cert, returns cert+key+CA
//! 4. Agent writes certs to disk
//! 5. Agent writes config YAML for future starts

use std::path::Path;

/// Perform agent enrollment and write certs + config to disk.
///
/// `gateway_url` is the base URL of the gateway (e.g., "https://gateway.example.com:4443").
/// `token` is the enrollment token (e.g., "ac_enroll_...").
/// `config_dir` is where to write certs and config (e.g., "/etc/appcontrol").
pub async fn enroll(gateway_url: &str, token: &str, config_dir: &str) -> anyhow::Result<()> {
    let hostname = crate::platform::gethostname();
    tracing::info!("Enrolling agent '{}' via gateway {}", hostname, gateway_url);

    // Convert WebSocket URL to HTTP URL for the enrollment HTTP POST request
    // (users often copy the wss:// URL from the UI enrollment dialog)
    let http_url = gateway_url
        .replace("wss://", "https://")
        .replace("ws://", "http://");

    // Build the enrollment URL (gateway /enroll endpoint)
    let enroll_url = format!("{}/enroll", http_url.trim_end_matches('/'));

    let body = serde_json::json!({
        "token": token,
        "hostname": hostname,
    });

    let client = reqwest::Client::builder()
        // Accept self-signed certs for initial enrollment (we don't have the CA yet)
        .danger_accept_invalid_certs(true)
        .build()?;

    let resp = client
        .post(&enroll_url)
        .json(&body)
        .send()
        .await
        .map_err(|e| anyhow::anyhow!("Failed to connect to gateway: {}", e))?;

    if !resp.status().is_success() {
        let status = resp.status();
        let body: serde_json::Value = resp.json().await.unwrap_or_default();
        let msg = body
            .get("message")
            .and_then(|m| m.as_str())
            .unwrap_or("Unknown error");
        return Err(anyhow::anyhow!(
            "Enrollment failed (HTTP {}): {}",
            status,
            msg
        ));
    }

    let resp_body: serde_json::Value = resp.json().await?;

    let cert_pem = resp_body
        .get("cert_pem")
        .and_then(|c| c.as_str())
        .ok_or_else(|| anyhow::anyhow!("Missing cert_pem in enrollment response"))?;
    let key_pem = resp_body
        .get("key_pem")
        .and_then(|k| k.as_str())
        .ok_or_else(|| anyhow::anyhow!("Missing key_pem in enrollment response"))?;
    let ca_pem = resp_body
        .get("ca_pem")
        .and_then(|c| c.as_str())
        .ok_or_else(|| anyhow::anyhow!("Missing ca_pem in enrollment response"))?;
    let agent_id = resp_body
        .get("agent_id")
        .and_then(|a| a.as_str())
        .unwrap_or("auto");
    let fingerprint = resp_body
        .get("fingerprint")
        .and_then(|f| f.as_str())
        .unwrap_or("?");

    // Write certificates to disk
    let dir = Path::new(config_dir);
    std::fs::create_dir_all(dir)?;

    let tls_dir = dir.join("tls");
    std::fs::create_dir_all(&tls_dir)?;

    let cert_path = tls_dir.join("agent.crt");
    let key_path = tls_dir.join("agent.key");
    let ca_path = tls_dir.join("ca.crt");

    std::fs::write(&cert_path, cert_pem)?;
    std::fs::write(&key_path, key_pem)?;
    std::fs::write(&ca_path, ca_pem)?;

    // Set key file permissions: owner read only
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&key_path, std::fs::Permissions::from_mode(0o600))?;
    }
    #[cfg(windows)]
    {
        // On Windows, make the key read-only (best effort — full ACLs require Win32 API)
        let mut perms = std::fs::metadata(&key_path)?.permissions();
        perms.set_readonly(true);
        std::fs::set_permissions(&key_path, perms)?;
    }

    // Convert gateway URL to WebSocket URL for the config
    let ws_url = gateway_url
        .replace("https://", "wss://")
        .replace("http://", "ws://");
    let ws_url = format!("{}/ws", ws_url.trim_end_matches('/'));

    // Write agent config YAML
    // Include data_dir pointing to the enrollment directory so the agent
    // doesn't require root permissions to write to /var/lib/appcontrol
    let config_content = format!(
        r#"# AppControl Agent Configuration
# Auto-generated by enrollment on {}

agent:
  id: "{}"

gateway:
  url: "{}"
  reconnect_interval_secs: 10

tls:
  enabled: true
  cert_file: "{}"
  key_file: "{}"
  ca_file: "{}"

# Data directory for agent state (buffer DB)
data_dir: "{}"
"#,
        chrono::Utc::now().to_rfc3339(),
        agent_id,
        ws_url,
        cert_path.display(),
        key_path.display(),
        ca_path.display(),
        dir.display(),
    );

    let config_path = dir.join("agent.yaml");
    std::fs::write(&config_path, config_content)?;

    println!();
    println!("  Agent Enrollment Successful");
    println!("  ===========================");
    println!();
    println!("  Agent ID:    {}", agent_id);
    println!("  Hostname:    {}", hostname);
    println!("  Fingerprint: {}", fingerprint);
    println!();
    println!("  cert:   {}", cert_path.display());
    println!("  key:    {}", key_path.display());
    println!("  ca:     {}", ca_path.display());
    println!("  config: {}", config_path.display());
    println!();

    #[cfg(unix)]
    println!(
        "  Start the agent with:\n    appcontrol-agent --config {}",
        config_path.display()
    );

    #[cfg(windows)]
    {
        println!(
            "  Start the agent with:\n    appcontrol-agent.exe --config \"{}\"",
            config_path.display()
        );
        println!();
        println!("  Install as Windows service:");
        println!(
            "    appcontrol-agent.exe service install --config \"{}\"",
            config_path.display()
        );
        println!("    sc start AppControlAgent");
    }

    Ok(())
}
